name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 # <--- Hier auf v4 aktualisiert

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2 # <--- Direkt auf die neuste Version aktualisiert

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.0 # <--- Ebenfalls auf eine aktuelle Version gehoben

    - name: Pakete wiederherstellen (Restore)
      run: nuget restore suota_pgp.sln

    - name: App kompilieren (Build)
      run: msbuild suota_pgp.sln /p:Configuration=Release /t:SignAndroidPackage

    - name: APK als Download bereitstellen
      uses: actions/upload-artifact@v4 # <--- Hier der entscheidende Fix auf v4!
      with:
        name: Suota-App-APK
        path: '**/*.apk'
